# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': '..'}

packages = \
['littlepaimon_utils',
 'littlepaimon_utils..venv.Lib.site-packages',
 'littlepaimon_utils..venv.Lib.site-packages.PIL',
 'littlepaimon_utils..venv.Lib.site-packages._distutils_hack',
 'littlepaimon_utils..venv.Lib.site-packages.anyio',
 'littlepaimon_utils..venv.Lib.site-packages.anyio._backends',
 'littlepaimon_utils..venv.Lib.site-packages.anyio._core',
 'littlepaimon_utils..venv.Lib.site-packages.anyio.abc',
 'littlepaimon_utils..venv.Lib.site-packages.anyio.streams',
 'littlepaimon_utils..venv.Lib.site-packages.certifi',
 'littlepaimon_utils..venv.Lib.site-packages.colorama',
 'littlepaimon_utils..venv.Lib.site-packages.h11',
 'littlepaimon_utils..venv.Lib.site-packages.h11.tests',
 'littlepaimon_utils..venv.Lib.site-packages.httpcore',
 'littlepaimon_utils..venv.Lib.site-packages.httpcore._async',
 'littlepaimon_utils..venv.Lib.site-packages.httpcore._sync',
 'littlepaimon_utils..venv.Lib.site-packages.httpcore.backends',
 'littlepaimon_utils..venv.Lib.site-packages.httpx',
 'littlepaimon_utils..venv.Lib.site-packages.httpx._transports',
 'littlepaimon_utils..venv.Lib.site-packages.idna',
 'littlepaimon_utils..venv.Lib.site-packages.pip',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.cli',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.commands',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.distributions',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.index',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.locations',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.metadata',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.models',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.network',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.operations',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.operations.build',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.operations.install',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.req',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.resolution',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.resolution.legacy',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.resolution.resolvelib',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.utils',
 'littlepaimon_utils..venv.Lib.site-packages.pip._internal.vcs',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.cachecontrol',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.certifi',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.chardet',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.chardet.cli',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.chardet.metadata',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.colorama',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.distlib',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.distlib._backport',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.html5lib',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.html5lib._trie',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.html5lib.filters',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.html5lib.treebuilders',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.idna',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.msgpack',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.packaging',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pep517',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pep517.in_process',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pkg_resources',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.platformdirs',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.progress',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pygments',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pygments.filters',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pygments.formatters',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pygments.lexers',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pygments.styles',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pyparsing',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.pyparsing.diagram',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.requests',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.resolvelib',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.resolvelib.compat',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.rich',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.tenacity',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.tomli',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.urllib3',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.urllib3.contrib',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.urllib3.packages',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.urllib3.util',
 'littlepaimon_utils..venv.Lib.site-packages.pip._vendor.webencodings',
 'littlepaimon_utils..venv.Lib.site-packages.pkg_resources',
 'littlepaimon_utils..venv.Lib.site-packages.pkg_resources._vendor',
 'littlepaimon_utils..venv.Lib.site-packages.pkg_resources._vendor.importlib_resources',
 'littlepaimon_utils..venv.Lib.site-packages.pkg_resources._vendor.jaraco',
 'littlepaimon_utils..venv.Lib.site-packages.pkg_resources._vendor.jaraco.text',
 'littlepaimon_utils..venv.Lib.site-packages.pkg_resources._vendor.more_itertools',
 'littlepaimon_utils..venv.Lib.site-packages.pkg_resources._vendor.packaging',
 'littlepaimon_utils..venv.Lib.site-packages.pkg_resources.extern',
 'littlepaimon_utils..venv.Lib.site-packages.rfc3986',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._distutils',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._distutils.command',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor.importlib_metadata',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor.importlib_resources',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor.jaraco',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor.jaraco.text',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor.more_itertools',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor.nspektr',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor.packaging',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools._vendor.tomli',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools.command',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools.config',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools.config._validate_pyproject',
 'littlepaimon_utils..venv.Lib.site-packages.setuptools.extern',
 'littlepaimon_utils..venv.Lib.site-packages.sniffio',
 'littlepaimon_utils..venv.Lib.site-packages.sniffio._tests',
 'littlepaimon_utils..venv.Lib.site-packages.tqdm',
 'littlepaimon_utils..venv.Lib.site-packages.tqdm.contrib',
 'littlepaimon_utils..venv.Lib.site-packages.wheel',
 'littlepaimon_utils..venv.Lib.site-packages.wheel.cli',
 'littlepaimon_utils..venv.Lib.site-packages.wheel.vendored',
 'littlepaimon_utils..venv.Lib.site-packages.wheel.vendored.packaging',
 'littlepaimon_utils..venv.Scripts']

package_data = \
{'': ['*'],
 'littlepaimon_utils': ['.idea/*',
                        '.idea/inspectionProfiles/*',
                        '.venv/*',
                        '.venv/Lib/site-packages/Pillow-9.2.0.dist-info/*',
                        '.venv/Lib/site-packages/anyio-3.6.1.dist-info/*',
                        '.venv/Lib/site-packages/certifi-2022.6.15.dist-info/*',
                        '.venv/Lib/site-packages/colorama-0.4.5.dist-info/*',
                        '.venv/Lib/site-packages/h11-0.12.0.dist-info/*',
                        '.venv/Lib/site-packages/h11/tests/data/*',
                        '.venv/Lib/site-packages/httpcore-0.15.0.dist-info/*',
                        '.venv/Lib/site-packages/httpx-0.23.0.dist-info/*',
                        '.venv/Lib/site-packages/idna-3.3.dist-info/*',
                        '.venv/Lib/site-packages/littlepaimon_utils-1.0.0.dist-info/*',
                        '.venv/Lib/site-packages/pip-22.0.4.dist-info/*',
                        '.venv/Lib/site-packages/rfc3986-1.5.0.dist-info/*',
                        '.venv/Lib/site-packages/setuptools-62.1.0.dist-info/*',
                        '.venv/Lib/site-packages/sniffio-1.2.0.dist-info/*',
                        '.venv/Lib/site-packages/tqdm-4.64.0.dist-info/*',
                        '.venv/Lib/site-packages/wheel-0.37.1.dist-info/*',
                        'dist/*']}

install_requires = \
['httpx>=0.23.0,<0.24.0', 'pillow>=9.1.1,<10.0.0', 'tqdm>=4.64.0,<5.0.0']

setup_kwargs = {
    'name': 'littlepaimon-utils',
    'version': '1.0.2',
    'description': '小派蒙的一些封装好的工具方法',
    'long_description': None,
    'author': '惜月',
    'author_email': '277073121@qq.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.7.3,<4.0.0',
}


setup(**setup_kwargs)
