"""empty message

Revision ID: 258421aeb463
Revises: 
Create Date: 2023-06-19 10:14:42.127886

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "258421aeb463"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_follow_withdraw_originmessage",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("adapter_name", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "nonebot_plugin_follow_withdraw_followmessage",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("adapter_name", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("origin_message_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_message_id"],
            ["nonebot_plugin_follow_withdraw_originmessage.message_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_follow_withdraw_followmessage")
    op.drop_table("nonebot_plugin_follow_withdraw_originmessage")
    # ### end Alembic commands ###
